CONTROLLER_HEART_BEAT_EXPIRATION = 30
WORKER_HEART_BEAT_INTERVAL = 15

LOGDIR = "."

# Model Constants
IGNORE_INDEX = -100
IMAGE_TOKEN_INDEX = -200
DEFAULT_IMAGE_TOKEN = "<image>"
DEFAULT_IMAGE_PATCH_TOKEN = "<im_patch>"
DEFAULT_IM_START_TOKEN = "<im_start>"
DEFAULT_IM_END_TOKEN = "<im_end>"

# Bounding Box Constants
BBOX_INDEX= -300
DEFAULT_BBOX_START_TOKEN = "<bbox_start>"
DEFAULT_BBOX_END_TOKEN = "<bbox_end>"

DEFAULT_BBOX_TOKEN = "<tubelet>"
DEFAULT_TEMPORAL_START_TOKEN = "<ts_start>"
DEFAULT_TEMPORAL_END_TOKEN = "<ts_end>"